#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 32

#define LV_USE_LOG 1
#define LV_LOG_PRINTF 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN

#define LV_MEM_SIZE (1024U * 1024U)

#define LV_FONT_MONTSERRAT_10 1
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_28 1
#define LV_FONT_MONTSERRAT_32 1

#define LV_USE_CHART 1
#define LV_USE_SNAPSHOT 1
#define LV_USE_FLEX 1
#define LV_USE_GRID 1
#define LV_USE_THORVG_INTERNAL 1
#define LV_USE_VECTOR_GRAPHIC 1
#define LV_USE_MATRIX 1
#define LV_USE_FLOAT 1
#define LV_USE_THEME_DEFAULT 1
#define LV_USE_THEME_SIMPLE 0
#define LV_USE_THEME_MONO 0

#define LV_BUILD_EXAMPLES 0

#endif